### ISSUE TITLE
[Question]关于借鉴与搬运的问题

### ISSUE THREAD

**Issue by gongfuture** [CAESIUS-TIM/ddnet-cfg#2]
请问阁下，是否可以在署名的情况下借鉴或搬运您此储存库中的内容？

**Comment by CAESIUS-TIM** [comment]
🉑(哇，被查成分了)

**Comment by gongfuture** [comment]
> <img alt="🉑" width="14" height="14" src="https://cdn.jsdelivr.net/gh/twitter/twemoji@14.0.2/assets/svg/1f251.svg">(哇，被查成分了)

（）
其实你之前star的时候我就看到了
